[package]
name = "ytp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
gtk4 = "0.8.1"
gstreamer = "0.22.4"
gst-plugin-gtk4 = "0.12.3"
tokio = "*"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.reqwest]
features = ["json"]
version = "0.12.4"
