[package]
name = "ytp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
gtk4 = "0.8.1"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.12.4"
